# Configuration for pull request documentation previews via Netlify

[build]
publish = "_site"
command = '''
  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  source $HOME/.poetry/env
  cd .. && \
  poetry install && \
  poetry run jupyter-book build book
  cd book
  jekyll build
'''
